/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TendenciaRouteImport } from './routes/tendencia'
import { Route as ResumenRouteImport } from './routes/resumen'
import { Route as NpsRouteImport } from './routes/nps'
import { Route as KpisRouteImport } from './routes/kpis'
import { Route as ImportarRouteImport } from './routes/importar'
import { Route as HealthRouteImport } from './routes/health'
import { Route as ContactosRouteImport } from './routes/contactos'
import { Route as ColaRouteImport } from './routes/cola'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const TendenciaRoute = TendenciaRouteImport.update({
  id: '/tendencia',
  path: '/tendencia',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumenRoute = ResumenRouteImport.update({
  id: '/resumen',
  path: '/resumen',
  getParentRoute: () => rootRouteImport,
} as any)
const NpsRoute = NpsRouteImport.update({
  id: '/nps',
  path: '/nps',
  getParentRoute: () => rootRouteImport,
} as any)
const KpisRoute = KpisRouteImport.update({
  id: '/kpis',
  path: '/kpis',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportarRoute = ImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactosRoute = ContactosRouteImport.update({
  id: '/contactos',
  path: '/contactos',
  getParentRoute: () => rootRouteImport,
} as any)
const ColaRoute = ColaRouteImport.update({
  id: '/cola',
  path: '/cola',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cola': typeof ColaRoute
  '/contactos': typeof ContactosRoute
  '/health': typeof HealthRoute
  '/importar': typeof ImportarRoute
  '/kpis': typeof KpisRoute
  '/nps': typeof NpsRoute
  '/resumen': typeof ResumenRoute
  '/tendencia': typeof TendenciaRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cola': typeof ColaRoute
  '/contactos': typeof ContactosRoute
  '/health': typeof HealthRoute
  '/importar': typeof ImportarRoute
  '/kpis': typeof KpisRoute
  '/nps': typeof NpsRoute
  '/resumen': typeof ResumenRoute
  '/tendencia': typeof TendenciaRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cola': typeof ColaRoute
  '/contactos': typeof ContactosRoute
  '/health': typeof HealthRoute
  '/importar': typeof ImportarRoute
  '/kpis': typeof KpisRoute
  '/nps': typeof NpsRoute
  '/resumen': typeof ResumenRoute
  '/tendencia': typeof TendenciaRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cola'
    | '/contactos'
    | '/health'
    | '/importar'
    | '/kpis'
    | '/nps'
    | '/resumen'
    | '/tendencia'
    | '/api/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cola'
    | '/contactos'
    | '/health'
    | '/importar'
    | '/kpis'
    | '/nps'
    | '/resumen'
    | '/tendencia'
    | '/api/chat'
  id:
    | '__root__'
    | '/'
    | '/cola'
    | '/contactos'
    | '/health'
    | '/importar'
    | '/kpis'
    | '/nps'
    | '/resumen'
    | '/tendencia'
    | '/api/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ColaRoute: typeof ColaRoute
  ContactosRoute: typeof ContactosRoute
  HealthRoute: typeof HealthRoute
  ImportarRoute: typeof ImportarRoute
  KpisRoute: typeof KpisRoute
  NpsRoute: typeof NpsRoute
  ResumenRoute: typeof ResumenRoute
  TendenciaRoute: typeof TendenciaRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tendencia': {
      id: '/tendencia'
      path: '/tendencia'
      fullPath: '/tendencia'
      preLoaderRoute: typeof TendenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resumen': {
      id: '/resumen'
      path: '/resumen'
      fullPath: '/resumen'
      preLoaderRoute: typeof ResumenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nps': {
      id: '/nps'
      path: '/nps'
      fullPath: '/nps'
      preLoaderRoute: typeof NpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kpis': {
      id: '/kpis'
      path: '/kpis'
      fullPath: '/kpis'
      preLoaderRoute: typeof KpisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importar': {
      id: '/importar'
      path: '/importar'
      fullPath: '/importar'
      preLoaderRoute: typeof ImportarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contactos': {
      id: '/contactos'
      path: '/contactos'
      fullPath: '/contactos'
      preLoaderRoute: typeof ContactosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cola': {
      id: '/cola'
      path: '/cola'
      fullPath: '/cola'
      preLoaderRoute: typeof ColaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ColaRoute: ColaRoute,
  ContactosRoute: ContactosRoute,
  HealthRoute: HealthRoute,
  ImportarRoute: ImportarRoute,
  KpisRoute: KpisRoute,
  NpsRoute: NpsRoute,
  ResumenRoute: ResumenRoute,
  TendenciaRoute: TendenciaRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
